#include <stdio.h>
#include <stdlib.h>
#include <curl/curl.h>
#include <json-c/json.h>
#include <stdbool.h>

 /* used code generated by the curl command line tool;
 All curl_easy_setopt() options are documented at:
 https://curl.haxx.se/libcurl/c/curl_easy_setopt.html
 *************************************************************************/
static size_t received_data(char *data, size_t size, size_t nmemb, void *userp) {
    // size is always 1 and is not used
    (void) size;
    (void) userp;

    // 'nmemb' may be 0 if the received file is empty. Exit early.
    if (nmemb == 0) {
        return 0;
    }

    // CURL does not guarantee that 'data' is null-terminated. Check this before
    // passing 'data' to json_tokener_parse().
    bool null_char_found = false;
    for (int i = 0; i < nmemb + 1; i++) {
        if (data[i] == '\0') {
            null_char_found = true;
            break;
        }
    }
    if (!null_char_found) {
        return 0;
    }

    // parse returned JSON data as city and weather forecast
    struct json_object *parsed_json;
    parsed_json = json_tokener_parse(data);
    if (!parsed_json) {
        return 0;
    }

    //get name of city
    struct json_object *name;
    json_object_object_get_ex(parsed_json, "name", &name);

    // TODO: check error status codes from above and below ( return errors handler)

    //get temperature from dict placed in main from parsed json
    struct json_object *main; //string where temperature is stored
    json_object_object_get_ex(parsed_json, "main", &main);
    //get temp key/value pair from main
    struct json_object *temperature;
    json_object_object_get_ex(main, "temp", &temperature);
    //grab temperature value
    double d_temperature = json_object_get_double(temperature);

    printf("The temperature in %s is %.2f °C\n", json_object_get_string(name), d_temperature);

    return nmemb;
}

int main(int argc, char **argv) {
    //fetch environment variable that contains weather API key
    char *api_key = getenv("API_KEY_WEATHER");
    if (!api_key) {
        fputs("Please add key to environment variable API_KEY_WEATHER", stderr);
    }
    //TODO: check and validate api key is correct format (check API to see if always same length and has correct characters)

    CURLcode ret;
    CURL *hnd = curl_easy_init();
    if (!hnd) {
        return 1;
    }

    // TODO: choose unit want temperature in, can be imperial(Fahrenheit) or
    // metric(Celsius). Temperature in Kelvin is used by default
    // if possible use locale as default and allow override with command line arg (getopt)

    //TODO: GET POSTCODE FROM USER // check correct input

    //Reach out to server and fetch data from openweathermap data returned is JSON
    char url[1000];
    //TODO: is length above enough? can be done dynamically or find max url length

    // TODO: location is hardcoded for now, take from user
    sprintf(
        url,
        "https://api.openweathermap.org/data/2.5/weather?q=London,GB&appid=%s&units=metric",
        api_key
    );
    curl_easy_setopt(hnd, CURLOPT_URL, url);

    curl_easy_setopt(hnd, CURLOPT_WRITEFUNCTION, received_data);
    ret = curl_easy_perform(hnd);

    // TODO: check curl_easy_perform error docs
    curl_easy_cleanup(hnd);

    return 0;
}
